function [x,resnorm,residual,exitflag,output,lambda,jacobian] = myMinLS2(xo,z,H,R,mu,Lb,Nx, Nt, md, mn, Um, Uz, as, Np, Ng, xS, xF, dt, OuterLoops)
func=@(x)funcF2(x,z,H,R,mu,Lb,Nx, Nt, md, mn, Um, Uz, as, Np, Ng, xS, xF, dt);
options = optimoptions('lsqnonlin','Algorithm','levenberg-marquardt',...
    'SpecifyObjectiveGradient',false,...
    'Diagnostics','off',...
    'Display','off',... %'iter-detailed', ...
    'MaxFunctionEvaluations',1e5, ...
    'MaxIterations',OuterLoops);
n = size(H,2);
ub = inf*ones(n,1);
lb = -ub;
[x,resnorm,residual,exitflag,output,lambda,jacobian] = lsqnonlin(func,xo,lb,ub,options);


